---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ecrs.afterpay.com
spec:
  group: afterpay.com
  scope: Namespaced
  names:
    plural: ecrs
    singular: ecr
    kind: ECR
    shortNames:
      - ecr
      - ecrs
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: ecrImageTagImmutability
          type: string
          jsonPath: .spec.ecrImageTagImmutability
          description: |-
            The configure of a repository to be immutable to prevent image tags from being overwritten.
            See https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-tag-mutability.html
        - name: ecrScanOnPush
          type: string
          jsonPath: .spec.ecrScanOnPush
          description: |-
            The configure of the image scan settings either for a new repository during creation or for an existing repository.
            See https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning.html
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              description: Spec defines the desired state of Ecr
              type: object
              properties:
                ecrImageTagImmutability:
                  type: string
                ecrScanOnPush:
                  type: string
                ecrPolicy:
                  type: string
            status:
              description: Status defines the observed state of Ecr
              type: object
              x-kubernetes-preserve-unknown-fields: true
