---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ecrs.afterpay.com
spec:
  group: afterpay.com
  scope: Namespaced
  subresources:
    status: {}
  names:
    plural: ecrs
    kind: ECR
    shortNames:
    - ecrs
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                ecrImageTagImmutability:
                  type: string
                ecrScanOnPush:
                  type: string
                ecrPolicy:
                  type: string
