---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ecr-operator-role
  labels:
    repo: ecr-operator
    addon: ecr-operator
rules:
  - apiGroups:
      - afterpay.com
    resources:
      - ecrs
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - afterpay.com
    resources:
      - ecrs/status
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ecr-operator-user-role
  labels:
    repo: ecr-operator
    addon: ecr-operator
rules:
  - apiGroups:
      - "ecrs.afterpay.com"
    resources:
      - ecrs
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - ecrs.afterpay.com
    resources:
      - ecrs/status
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ecr-operator-rolebinding
  labels:
    repo: ecr-operator
    addon: ecr-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ecr-operator-role
subjects:
  - kind: ServiceAccount
    name: ecr-operator
    namespace: kube-system
