---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-operator
  namespace: kube-system
  labels:
    repo: ecr-operator
    addon: ecr-operator
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<< .config.awsAccountId >>:role/k8s/<< .config.clusterName >>/kubesystem/ecr-operator-<< .config.clusterName >>
