---
apiVersion: afterpay.com/v1alpha1
kind: ECR
metadata:
  name: delete-me-ecr
  namespace: pe
spec:
  ecrImageTagImmutability: "true"
  ecrScanOnPush: "true"
  ecrPolicy: '{
    "Version": "2008-10-17",
    "Statement": [
      {
        "Sid": "ecr-access",
        "Effect": "Allow",
        "Principal": {
          "AWS": [
            "arn:aws:iam::723236915308:root",
            "arn:aws:iam::568431661506:root"
            "arn:aws:iam::830726149330:root"
          ]
        },
        "Action": [
          "ecr:BatchCheckLayerAvailability",
          "ecr:BatchGetImage",
          "ecr:CompleteLayerUpload",
          "ecr:GetDownloadUrlForLayer",
          "ecr:InitiateLayerUpload",
          "ecr:PutImage",
          "ecr:UploadLayerPart"
        ]
      }
    ]
  }'
